# Generated by Django 4.2.11 on 2024-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_sayhi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(choices=[('web_app', 'Web App'), ('full_stack_app', 'Full Stack App'), ('android_app', 'Android App'), ('ios_app', 'Ios App'), ('rest_api', 'REST API'), ('web_backend', 'Web Backend'), ('core_python', 'Core Python'), ('other', 'Other')], max_length=50),
        ),
    ]
