# Generated by Django 4.2.11 on 2024-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=155)),
                ('githublink', models.CharField()),
                ('details', models.CharField()),
            ],
        ),
    ]
