# Generated by Django 4.2.11 on 2024-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='Projects/banner'),
        ),
    ]
