# Generated by Django 4.2.11 on 2024-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpg', '0002_projects_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
