# Generated by Django 4.2.11 on 2024-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpg', '0003_alter_projects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.CharField(max_length=200),
        ),
    ]
