# Generated by Django 4.2.11 on 2024-04-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpg', '0004_alter_projects_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.CharField(max_length=700),
        ),
    ]
