# Generated by Django 4.2.11 on 2024-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpg', '0005_alter_projects_description_alter_projects_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
